// <auto-generated />
using System;
using Activity2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Activity2.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250829031957_InitialDataSeed")]
    partial class InitialDataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Activity2.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagIbigNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("102441c3-1d91-4351-978e-d2f4eed95e77"),
                            Email = "jeskhasamanthaderama@gmail.com",
                            IsDeleted = false,
                            Name = "Summi Derama",
                            PagIbigNumber = "21101228",
                            Position = "Developer",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("7a877bb7-ad4b-448b-bfd3-f6d85910f798"),
                            Email = "jansenchoi@gmail.com",
                            IsDeleted = false,
                            Name = "Jansen Choi",
                            PagIbigNumber = "21101228",
                            Position = "Scrum Master",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("aae6d8f1-f6f6-4a0c-9651-cd988730387a"),
                            Email = "joshlui@gmail.com",
                            IsDeleted = false,
                            Name = "Josh Lui",
                            PagIbigNumber = "21101228",
                            Position = "Project Owner",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
