// <auto-generated />
using System;
using Activity2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Activity2.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250829032202_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Activity2.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagIbigNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("75ca3ee7-652e-49b5-8888-fde0d78d8f1f"),
                            Email = "jeskhasamanthaderama@gmail.com",
                            IsDeleted = false,
                            Name = "Summi Derama",
                            PagIbigNumber = "21101228",
                            Position = "Developer",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("77356cd1-b1cd-49cd-a2cf-5732eeb4b36a"),
                            Email = "jansenchoi@gmail.com",
                            IsDeleted = false,
                            Name = "Jansen Choi",
                            PagIbigNumber = "21101228",
                            Position = "Scrum Master",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("79f5d023-5414-4862-a28a-10e7d6cd1270"),
                            Email = "joshlui@gmail.com",
                            IsDeleted = false,
                            Name = "Josh Lui",
                            PagIbigNumber = "21101228",
                            Position = "Project Owner",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
