// <auto-generated />
using System;
using Activity2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Activity2.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20250829032317_DataSeed2")]
    partial class DataSeed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Activity2.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagIbigNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("58b06f23-3540-48cb-835b-cf2520a7f01c"),
                            Email = "jeskhasamanthaderama@gmail.com",
                            IsDeleted = false,
                            Name = "Summi Derama",
                            PagIbigNumber = "21101228",
                            Position = "Developer",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("74e2e28a-e237-4d2e-89da-4f633854ac95"),
                            Email = "jansenchoi@gmail.com",
                            IsDeleted = false,
                            Name = "Jansen Choi",
                            PagIbigNumber = "21101228",
                            Position = "Scrum Master",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("79951851-4769-4125-acd8-cf06d7107a2b"),
                            Email = "joshlui@gmail.com",
                            IsDeleted = false,
                            Name = "Josh Lui",
                            PagIbigNumber = "21101228",
                            Position = "Project Owner",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
