// <auto-generated />
using System;
using Activity2.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Activity2.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    partial class EmployeeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Activity2.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PagIbigNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSSNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fafe3893-193c-4e84-9001-ffe1f478e914"),
                            Email = "jeskhasamanthaderama@gmail.com",
                            IsDeleted = false,
                            Name = "Summi Derama",
                            PagIbigNumber = "21101228",
                            Position = "Developer",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("e1c93f76-c6a4-4b1a-b423-aa7c5e1a2005"),
                            Email = "jansenchoi@gmail.com",
                            IsDeleted = false,
                            Name = "Jansen Choi",
                            PagIbigNumber = "21101228",
                            Position = "Scrum Master",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        },
                        new
                        {
                            Id = new Guid("20176a93-4603-4cce-9d1b-884d8b3bfea6"),
                            Email = "joshlui@gmail.com",
                            IsDeleted = false,
                            Name = "Josh Lui",
                            PagIbigNumber = "21101228",
                            Position = "Project Owner",
                            SSSNumber = "21101228",
                            Salary = 28000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
